# Generated by Django 4.0.1 on 2022-01-31 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seats_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=101, null=True)),
                ('destinations', models.CharField(choices=[('New York to Washington DC', 'New York to Washington DC'), ('Washington DC to Miami', 'Washington DC to Miami'), ('Los Angeles to Dalas', 'Los Angeles to Dalas')], max_length=100)),
                ('gate', models.CharField(blank=True, choices=[('24F', '24F'), ('1A', '1A'), ('14D', '14D'), ('6B', '6B')], max_length=10)),
                ('flight_status', models.CharField(choices=[('Waiting for cheking-in', 'Waiting for cheking-in'), ('Check-in', 'Check-in'), ('Boarding', 'Boarding'), ('Boarding completed', 'Boarding completed'), ('Delayed', 'Delayed')], max_length=100)),
                ('date', models.DateField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seats_number', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(blank=True, choices=[(0, 'None'), (1, 'Fish'), (2, 'Chicken'), (3, 'Pork')], default=0, max_length=100, null=True)),
                ('luggage', models.CharField(blank=True, choices=[(0, 'None'), (1, 'Small'), (2, 'Big'), (3, 'Extra Big')], default=0, max_length=100, null=True)),
                ('ticket_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.passenger')),
            ],
        ),
    ]
