# Generated by Django 4.0.1 on 2022-02-01 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Registred', 'Registred')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_status',
            field=models.CharField(choices=[('Waiting for cheking-in', 'Waiting for cheking-in'), ('Check-in', 'Check-in'), ('Boarding', 'Boarding'), ('Boarding completed', 'Boarding completed'), ('Delayed', 'Delayed'), ('Canceled', 'Canceled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='luggage',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Small', 'Small'), ('Big', 'Big'), ('Extra Big', 'Extra Big')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='lunch',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Fish', 'Fish'), ('Chicken', 'Chicken'), ('Pork', 'Pork')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='ticket_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flights.ticket'),
        ),
    ]
