# Generated by Django 4.0.1 on 2022-02-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_ticket_status_alter_flight_flight_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
