# Generated by Django 4.0.1 on 2022-02-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='seats_number',
        ),
    ]
