# Generated by Django 4.0.1 on 2022-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='role',
            field=models.CharField(blank=True, choices=[('Passanger', 'Passanger'), ('Gate_manager', 'Gate_manager'), ('Check_in_manager', 'Check_in_manager'), ('Supervisor', 'Supervisor')], default='Passanger', max_length=100, null=True),
        ),
    ]
