# Generated by Django 4.0.1 on 2022-02-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Registred', 'Registred')], default='None', max_length=100),
        ),
    ]
